"""
This module will contain the functions to extract data from the grants and put them
into a standard format for the embedding process.

Grants_ai Table Schema (~ indicated fields that need to be generated by AI):
  id BIGSERIAL PRIMARY KEY,
  opportunity_id TEXT NOT NULL,
  model TEXT,
  prompt_version TEXT,
  ~purpose TEXT,
  ~funding_topics JSONB,
  ~desired_outcomes JSONB,
  ~project_examples JSONB,
  ~problems_addressed JSONB,
  ~common_search_queries JSONB,
  embedding_document TEXT,
  embedding VECTOR(1536),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
"""

from __future__ import annotations

import json
from typing import Any

from db.db_util import row_get
from pipelines.ai_utils.embed import build_embedding_document
from pipelines.ai_utils.llm_clients import LLMService
from pipelines.ai_utils.prompts import extract_grants_ai_required_fields

EXTRACTION_SOURCE_FIELDS = (
    "title",
    "agency",
    "description",
    "eligibility_description",
    "eligibilities",
)


def _normalize_extraction_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value).strip()


def has_extractable_description(data: dict) -> bool:
    return bool((data.get("description") or "").strip())


def extraction_source_changed(old_data: dict | None, new_data: dict) -> bool:
    """True when fields that feed the extraction prompt changed."""
    if old_data is None:
        return True
    for field in EXTRACTION_SOURCE_FIELDS:
        old_val = _normalize_extraction_value(old_data.get(field))
        new_val = _normalize_extraction_value(new_data.get(field))
        if old_val != new_val:
            return True
    return False


def should_sync_grants_ai(new_data: dict, old_data: dict | None = None) -> bool:
    """
    Decide whether to run LLM extraction for this grant.

    Re-extract only when description exists and extraction-source fields changed.
    Deadline, status, funding amount, and similar metadata changes are ignored.
    """
    if not has_extractable_description(new_data):
        return False
    if old_data is None:
        return True
    return extraction_source_changed(old_data, new_data)


def grant_from_normalized(normalized: dict) -> dict:
    """Map normalized ingestion payload to the shape used by extraction/embed."""
    oid = normalized.get("id") or normalized.get("opportunity_id")
    return {
        "opportunity_id": str(oid),
        "title": normalized.get("title"),
        "agency": normalized.get("agency"),
        "description": normalized.get("description"),
        "eligibility_description": normalized.get("eligibility_description"),
        "eligibilities": normalized.get("eligibilities"),
    }


def fetch_grants_for_extraction(
    conn: Any,
    *,
    limit: int | None = None,
    status_equals: str | None = None,
    skip_existing: bool = False,
) -> list[dict]:
    """Grants with enough text for AI extraction."""
    clauses = [
        "(g.description IS NOT NULL AND TRIM(g.description) != '')",
    ]
    params: list[object] = []

    if status_equals:
        clauses.append("g.status = %s")
        params.append(status_equals)

    if skip_existing:
        clauses.append(
            "NOT EXISTS ("
            "SELECT 1 FROM grants_ai ga WHERE ga.opportunity_id = g.opportunity_id"
            ")"
        )

    where = " AND ".join(clauses)
    sql = f"""
        SELECT
            g.opportunity_id,
            g.number,
            g.title,
            g.agency,
            g.status,
            g.description,
            g.eligibility_description,
            g.eligibilities,
            g.grant_gov_url
        FROM grants g
        WHERE {where}
        ORDER BY g.opportunity_id
    """
    if limit is not None:
        sql += f" LIMIT {int(limit)}"

    cur = conn.cursor()
    cur.execute(sql, tuple(params))
    rows = cur.fetchall()

    out: list[dict] = []
    for row in rows:
        out.append(
            {
                "opportunity_id": row_get(row, "opportunity_id", 0),
                "number": row_get(row, "number", 1),
                "title": row_get(row, "title", 2),
                "agency": row_get(row, "agency", 3),
                "status": row_get(row, "status", 4),
                "description": row_get(row, "description", 5),
                "eligibility_description": row_get(row, "eligibility_description", 6),
                "eligibilities": row_get(row, "eligibilities", 7),
                "grant_gov_url": row_get(row, "grant_gov_url", 8),
            }
        )
    return out


def count_grants_pending_extraction(
    conn: Any,
    *,
    status_equals: str | None = None,
) -> int:
    """How many grants still need extraction into grants_ai."""
    clauses = [
        "(g.description IS NOT NULL AND TRIM(g.description) != '')",
        "NOT EXISTS ("
        "SELECT 1 FROM grants_ai ga WHERE ga.opportunity_id = g.opportunity_id"
        ")",
    ]
    params: list[object] = []

    if status_equals:
        clauses.append("g.status = %s")
        params.append(status_equals)

    where = " AND ".join(clauses)
    sql = f"SELECT COUNT(*) FROM grants g WHERE {where}"
    cur = conn.cursor()
    cur.execute(sql, tuple(params))
    row = cur.fetchone()
    if row is None:
        return 0
    if isinstance(row, dict):
        return int(next(iter(row.values())))
    return int(row[0])


def _json_field(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False)


def extraction_dict_to_row_fields(data: dict) -> tuple:
    """Map LLM JSON to grants_ai column values (purpose + JSON list fields)."""
    return (
        data.get("purpose"),
        _json_field(data.get("funding_topics")),
        _json_field(data.get("desired_outcomes")),
        _json_field(data.get("project_examples")),
        _json_field(data.get("problems_addressed")),
        _json_field(data.get("common_search_queries")),
    )


def extract_grant_ai_fields(grant: dict, llm_service: LLMService) -> dict | None:
    """Run LLM extraction for one grant. Returns parsed JSON or None."""
    return extract_grants_ai_required_fields(grant, llm_service)


def create_grants_ai_row(conn, grant: dict, llm_service: LLMService) -> bool:
    """
    Extract fields for one grant and insert a row into grants_ai.
    """
    return sync_grants_ai_for_grant(conn, grant, llm_service)


def save_grants_ai_extraction(
    conn,
    opportunity_id: str,
    extracted_fields: tuple,
    *,
    embedding_document: str | None = None,
) -> bool:
    """
    Insert or update extracted fields. Clears embedding so it can be regenerated.
    """
    cursor = conn.cursor()
    try:
        query = """
        INSERT INTO grants_ai (
            opportunity_id, purpose, funding_topics, desired_outcomes,
            project_examples, problems_addressed, common_search_queries,
            embedding_document
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT(opportunity_id) DO UPDATE SET
            purpose = excluded.purpose,
            funding_topics = excluded.funding_topics,
            desired_outcomes = excluded.desired_outcomes,
            project_examples = excluded.project_examples,
            problems_addressed = excluded.problems_addressed,
            common_search_queries = excluded.common_search_queries,
            embedding_document = excluded.embedding_document,
            embedding = NULL,
            model = NULL
        """
        cursor.execute(
            query,
            (
                opportunity_id,
                extracted_fields[0],
                extracted_fields[1],
                extracted_fields[2],
                extracted_fields[3],
                extracted_fields[4],
                extracted_fields[5],
                embedding_document,
            ),
        )
        conn.commit()
        return True
    except Exception as e:
        conn.rollback()
        print(f"Error saving grants_ai extraction for {opportunity_id}: {e}")
        return False


def sync_grants_ai_for_grant(conn, grant: dict, llm_service: LLMService) -> bool:
    """Extract with the LLM and upsert grants_ai (clears any prior embedding)."""
    extracted = extract_grant_ai_fields(grant, llm_service)
    if not extracted:
        return False
    extracted_fields = extraction_dict_to_row_fields(extracted)
    embedding_document = build_embedding_document(
        extracted,
        title=grant.get("title"),
        agency=grant.get("agency"),
    )
    return save_grants_ai_extraction(
        conn,
        grant["opportunity_id"],
        extracted_fields,
        embedding_document=embedding_document,
    )


def insert_grants_ai_row(
    conn,
    opportunity_id: str,
    extracted_fields: tuple,
    *,
    embedding_document: str | None = None,
) -> bool:
    """Insert extracted fields into grants_ai without updating existing rows."""
    return save_grants_ai_extraction(
        conn,
        opportunity_id,
        extracted_fields,
        embedding_document=embedding_document,
    )
